# @package _global_
defaults:
  - /model/layers@model.attention_layer: attention

model:
  _target_: graph_attention.models.simple_vit.SimpleViT
  image_size: 32
  patch_size: 4
  dim: 256
  depth: 6
  num_heads: 4
  mlp_ratio: 2
  
